<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MasterOfPasswords.Mapper\MasterOfPasswords.Mapper.csproj" />
      <ProjectReference Include="..\MasterOfPasswords.Models\MasterOfPasswords.Models.csproj" />
      <ProjectReference Include="..\MasterOfPasswords\MasterOfPasswords.csproj" />
    </ItemGroup>

</Project>
